services:
  # Your Node.js Application
  app:
    build: .
    container_name: cloud-server
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_USER=admin-user
      - DB_PASSWORD=Maanas1234
      - DB_HOST=postgres
      - DB_NAME=cloud-db
      - JWT_SECRET=5fb93c7d2599e947e27f4162c2ecef7a9cab375e523073367a84111927a5b400e1a50f89a35b5595cade773af33ddcc573be73216dc81cf24a77e7bebafccfcd
    depends_on:
      - postgres
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: cloud-server-db
    environment:
      - POSTGRES_USER=admin-user
      - POSTGRES_PASSWORD=Maanas1234
      - POSTGRES_DB=cloud-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # PGAdmin (Database Management Tool)
  pgadmin:
    image: dpage/pgadmin4
    container_name: cloud-server-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cloud.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8000:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
